# 가설 N: 부양가족(Dependents): 홍지윤
* 부양가족이 있는 고객은 안정적인 보장을 원하므로, 1인 가구보다 이탈률이 낮을 것이다.
* 특히 가족 전체를 보장하는 **Home(화재)** 이나 **Health** 보험의 이탈률이 1인 가구보다 현저히 낮을 것이다.

In [5]:
# import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from src.preprocess import load_data

## 데이터 수집

In [7]:
# 1. 데이터 로드
df = load_data()
df

호출

,customer_id,as_of_date,region_name,age,age_band,marital_status,customer_tenure_months,multi_policy_flag,num_policies,policy_type,...,avg_settlement_time_days,days_since_last_claim,num_contacts_12m,complaint_flag,complaint_resolution_days,quote_requested_flag,coverage_downgrade_flag,churn_flag,churn_type,churn_probability_true
0,1,2025-12-31,Manawatu-Whanganui,24,18-24,Married,128,1,4,Auto,...,7,1616,0,0,0,0,0,0,No churn,0.048626
1,2,2025-12-31,Auckland,70,65-74,Married,76,1,3,Auto,...,15,1760,1,0,0,0,0,0,No churn,0.067888
2,3,2025-12-31,Bay of Plenty,62,55-64,Married,129,0,1,Auto,...,24,1581,1,0,0,0,0,0,No churn,0.223765
3,4,2025-12-31,Bay of Plenty,47,45-54,Single,104,0,1,Auto,...,17,1688,1,0,0,0,0,0,No churn,0.602455
4,5,2025-12-31,Bay of Plenty,47,45-54,Married,22,1,3,Life,...,24,1592,1,0,0,0,0,0,No churn,0.050723
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,2025-12-31,Auckland,55,55-64,Single,25,0,1,Life,...,14,1379,2,0,0,0,0,0,No churn,0.260704
49996,49997,2025-12-31,Wellington,85,75+,Married,89,0,1,Health,...,26,741,0,0,0,0,0,1,Other,0.584094
49997,49998,2025-12-31,Auckland,28,25-34,Single,82,0,1,Home,...,26,320,5,0,0,0,0,0,No churn,0.179628
49998,49999,2025-12-31,Auckland,39,35-44,Single,55,0,1,Home,...,24,508,4,0,0,0,0,0,No churn,0.210082
49999,50000,2025-12-31,Auckland,61,55-64,Single,146,0,1,Travel,...,19,422,1,0,0,0,0,0,No churn,0.165199

In [17]:
df.head()

df.loc[:, 'is_churn'] = df['churn_flag']

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 41 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  50000 non-null  int64
 1   as_of_date                   50000 non-null  str
 2   region_name                  50000 non-null  str
 3   age                          50000 non-null  int64
 4   age_band                     50000 non-null  str
 5   marital_status               50000 non-null  str
 6   customer_tenure_months       50000 non-null  int64
 7   multi_policy_flag            50000 non-null  int64
 8   num_policies                 50000 non-null  int64
 9   policy_type                  50000 non-null  str
 10  renewal_month                50000 non-null  int64
 11  current_premium              50000 non-null  float64
 12  premium_last_year            50000 non-null  float64
 13  premium_change_pct           50000 non-null  float64
 14  num_price_increases_last_3y  50000 non-null  int64
 15  coverage_amount              50000 non-null  float64
 16  premium_to_coverage_ratio    50000 non-null  float64
 17  payment_frequency            50000 non-null  str
 18  autopay_enabled              50000 non-null  int64
 19  late_payment_count_12m       50000 non-null  int64
 20  missed_payment_flag          50000 non-null  int64
 21  payment_method_change_flag   50000 non-null  int64
 22  num_claims_12m               50000 non-null  int64
 23  num_approved_claims_12m      50000 non-null  int64
 24  num_rejected_claims_12m      50000 non-null  int64
 25  num_pending_claims_12m       50000 non-null  int64
 26  avg_claim_amount             50000 non-null  float64
 27  total_claim_amount_12m       50000 non-null  float64
 28  total_payout_amount_12m      50000 non-null  float64
 29  payout_ratio_12m             50000 non-null  float64
 30  avg_settlement_time_days     50000 non-null  int64
 31  days_since_last_claim        50000 non-null  int64
 32  num_contacts_12m             50000 non-null  int64
 33  complaint_flag               50000 non-null  int64
 34  complaint_resolution_days    50000 non-null  int64
 35  quote_requested_flag         50000 non-null  int64
 36  coverage_downgrade_flag      50000 non-null  int64
 37  churn_flag                   50000 non-null  int64
 38  churn_type                   50000 non-null  str
 39  churn_probability_true       50000 non-null  float64
 40  is_churn                     50000 non-null  int64
dtypes: float64(10), int64(24), str(7)
memory usage: 18.0 MB

In [23]:
# 2. 전체 이탈률 비교 (Married vs Single)
overall_churn = df.groupby('marital_status')['is_churn'].sum().reset_index()
overall_churn

# 3. 상품군별 이탈률 비교
# policy_churn = df.groupby(['policy_type', 'marital_status'])['is_churn'].sum().reset_index()
# policy_churn

# # 시각화 설정
# sns.set_theme(style="whitegrid")
# plt.figure(figsize=(12, 5))
#
# # 그래프 1: 전체 이탈률
# plt.subplot(1, 2, 1)
# sns.barplot(data=overall_churn, x='marital_status', y='is_churn', palette='viridis')
# plt.title('Overall Churn Rate by Marital Status')
# plt.ylabel('Churn Rate')
#
# # 그래프 2: 상품군별 이탈률
# plt.subplot(1, 2, 2)
# sns.barplot(data=policy_churn, x='policy_type', y='is_churn', hue='marital_status')
# plt.title('Churn Rate by Policy Type & Marital Status')
# plt.ylabel('Churn Rate')
# plt.xticks(rotation=45)
#
# plt.tight_layout()
# plt.show()

  marital_status  is_churn
0        Married      8298
1         Single      6785